### ISSUE TITLE
Version 3 and 4 broke loading data from LL in scripts

### ISSUE THREAD

**Issue by GLAD-DE** [ivanhofer/typesafe-i18n#180]
### Version

4.1.1

### Describe the bug

In version 2 I could load and access LL from typescript files with:
```typescript
import LL from "$i18n/i18n-svelte";

function example(): string {
	return LL.HI({ year: 2021 });
}
```

This no longer works in version 3 and 4. Instead the following error is printed:
```__vite_ssr_import_0__.default.HI is not a function```

### Reproduction

[See this repo for an example](https://github.com/GLAD-DE/typesafe-i18n-demo-sveltekit/tree/9f25e23e2a0d5ba2d38f384eee6f57eddf2fcfc4)

### Logs

```shell
__vite_ssr_import_0__.default.HI is not a function
TypeError: __vite_ssr_import_0__.default.HI is not a function
    at Module.attemptToReadFromLL (/home/user/typesafe-i18n-demo-sveltekit/src/lib/sampleScript.ts:4:14)
    at index.svelte:27:69
    at Object.$$render (/home/user/typesafe-i18n-demo-sveltekit/node_modules/svelte/internal/index.js:1745:22)
    at Object.default (root.svelte:43:47)
    at eval (/src/routes/__layout.svelte:58:66)
    at Object.$$render (/home/user/typesafe-i18n-demo-sveltekit/node_modules/svelte/internal/index.js:1745:22)
    at root.svelte:37:45
    at $$render (/home/user/typesafe-i18n-demo-sveltekit/node_modules/svelte/internal/index.js:1745:22)
    at Object.render (/home/user/typesafe-i18n-demo-sveltekit/node_modules/svelte/internal/index.js:1753:26)
    at render_response (file:////home/user/typesafe-i18n-demo-sveltekit/.svelte-kit/runtime/server/index.js:1181:28)
```

### Config

```json
{
   "$schema": "https://unpkg.com/typesafe-i18n@4.1.1/schema/typesafe-i18n.json",
   "adapter": "svelte"
}
```

### Additional information

I encountered this issue when using sveltekit.

**Comment by ivanhofer** [comment]
@GLAD-DE 

you can use it like this:

```ts
import { get } from 'svelte/stores'
import LL from '$i18n/i18n-svelte'

function example(): string {
   return get(LL).HI({ year: 2021 });
}
```

I need to mention this in the docs.

**Comment by ivanhofer** [comment]
I have updated the migration guide to also mention this breaking change #163

**Comment by GLAD-DE** [comment]
Thank you :)

There is a small mistake in the discussion #163:

It should be ```import { get } from 'svelte/store'``` instead of ```import { get } from 'svelte/stores'``` (no leading 's')
