### ISSUE TITLE
Internal server error: Missing "./utils" specifier in "typesafe-i18n" package

### ISSUE THREAD

**Issue by Cluster2a** [ivanhofer/typesafe-i18n#589]
### Version

5.23.0

### Describe the bug

After upgrading from 5.20.0 to 5.23.0 I am getting the following error:
![image](https://user-images.githubusercontent.com/84905165/216783576-bcc95f47-889e-4f65-9e49-fff3e203553d.png)

I deleted all the auto-generated files and reran typesafe-i18n, without any success.

### Reproduction

Will create a repo, if needed.

### Logs

```sh
Internal server error: Missing "./utils" specifier in "typesafe-i18n" package
Plugin: vite:import-analysis
File: /app/src/i18n/i18n-util.ts
at e (file:///app/node_modules/.pnpm/vite@4.1.1_sass@1.58.0/node_modules/vite/dist/node/chunks/dep-3007b26d.js:14845:25)
at n (file:///app/node_modules/.pnpm/vite@4.1.1_sass@1.58.0/node_modules/vite/dist/node/chunks/dep-3007b26d.js:14845:627)
at o (file:///app/node_modules/.pnpm/vite@4.1.1_sass@1.58.0/node_modules/vite/dist/node/chunks/dep-3007b26d.js:14845:1276)
at resolveExports (file:///app/node_modules/.pnpm/vite@4.1.1_sass@1.58.0/node_modules/vite/dist/node/chunks/dep-3007b26d.js:22032:20)
at resolveDeepImport (file:///app/node_modules/.pnpm/vite@4.1.1_sass@1.58.0/node_modules/vite/dist/node/chunks/dep-3007b26d.js:22051:31)
at tryNodeResolve (file:///app/node_modules/.pnpm/vite@4.1.1_sass@1.58.0/node_modules/vite/dist/node/chunks/dep-3007b26d.js:21736:20)
at Context.resolveId (file:///app/node_modules/.pnpm/vite@4.1.1_sass@1.58.0/node_modules/vite/dist/node/chunks/dep-3007b26d.js:21487:28)
at Object.resolveId (file:///app/node_modules/.pnpm/vite@4.1.1_sass@1.58.0/node_modules/vite/dist/node/chunks/dep-3007b26d.js:41587:46)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async TransformContext.resolve (file:///app/node_modules/.pnpm/vite@4.1.1_sass@1.58.0/node_modules/vite/dist/node/chunks/dep-3007b26d.js:41334:23)
```

### Config

```JSON
{
   "baseLocale": "de",
   "adapter": "svelte",
   "$schema": "https://unpkg.com/typesafe-i18n@5.23.0/schema/typesafe-i18n.json"
}
```

### Additional information

  System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (20) x64 Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
    Memory: 14.78 GB / 31.25 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 19.4.0 - ~/.nvm/versions/node/v19.4.0/bin/node
    npm: 9.2.0 - ~/.nvm/versions/node/v19.4.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.74
    Firefox: 109.0.1

**Comment by Cluster2a** [comment]
I rolled back to 5.23.0 and tried every version from there. For some reason, 5.23.0 is working now.
Closing this issue.

**Comment by timothyallan** [comment]
I'm also getting this with 5.23.0 trying to do a build with vite + solid... dev works fine however.
Confirmed that downgrading to 5.22.0 fixes it.

**Comment by proddy** [comment]
Same problem here. Rolling back to 5.22.0 for now

**Comment by ivanhofer** [comment]
`5.23.1` should work again

**Comment by proddy** [comment]
different errors now. Haven't looked into why, just reporting quickly here...

```
Module not found: Error: Can't resolve 'module' in '.../interface/node_modules/typesafe-i18n/utils'
ERROR in ./node_modules/typesafe-i18n/utils/index.mjs 1:0-39
Module not found: Error: Can't resolve 'module' in '.../interface/node_modules/typesafe-i18n/utils'

ERROR in ./node_modules/typesafe-i18n/utils/index.mjs 3:0-36
Module not found: Error: Can't resolve 'url' in '.../interface/node_modules/typesafe-i18n/utils'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
        - install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "url": false }

```

**Comment by ivanhofer** [comment]
Ok then it is probably an issue with the transformation of `lodash.merge`.
It did work in my test application. I would need a test repo to investigate it further. Can you please set one up for me?

**Comment by ivanhofer** [comment]
let's move the discussion to #592
