### ISSUE TITLE
Vite/SvelteKit crashes on finding initExtendDirectory

### ISSUE THREAD

**Issue by ciscoheat** [ivanhofer/typesafe-i18n#590]
### Version

5.23.0

### Describe the bug

After upgrading to 5.23.0, Vite/SvelteKit doesn't start anymore with `vite dev`.

### Reproduction

Follow the instructions here to setup a minimal example: https://blog.encodeart.dev/typesafe-i18n-with-sveltekit

When importing LL with:
```
import { LL } from '$lib/i18n/i18n-svelte';
```

It will give this error:

```
20:26:16 [vite] hmr update /src/routes/+page.svelte
Missing "./utils" specifier in "typesafe-i18n" package
20:26:16 [vite] Internal server error: Missing "./utils" specifier in "typesafe-i18n" package
  Plugin: vite:import-analysis
  File: E:/Projects/TEST/i18nbug/src/lib/i18n/i18n-util.ts
      at e (file:///E:/Projects/TEST/i18nbug/node_modules/.pnpm/vite@4.1.1/node_modules/vite/dist/node/chunks/dep-3007b26d.js:14845:25)
      at n (file:///E:/Projects/TEST/i18nbug/node_modules/.pnpm/vite@4.1.1/node_modules/vite/dist/node/chunks/dep-3007b26d.js:14845:627)
      at o (file:///E:/Projects/TEST/i18nbug/node_modules/.pnpm/vite@4.1.1/node_modules/vite/dist/node/chunks/dep-3007b26d.js:14845:1276)
      at resolveExports (file:///E:/Projects/TEST/i18nbug/node_modules/.pnpm/vite@4.1.1/node_modules/vite/dist/node/chunks/dep-3007b26d.js:22032:20)
      at resolveDeepImport (file:///E:/Projects/TEST/i18nbug/node_modules/.pnpm/vite@4.1.1/node_modules/vite/dist/node/chunks/dep-3007b26d.js:22051:31)
      at tryNodeResolve (file:///E:/Projects/TEST/i18nbug/node_modules/.pnpm/vite@4.1.1/node_modules/vite/dist/node/chunks/dep-3007b26d.js:21736:20)
      at Context.resolveId (file:///E:/Projects/TEST/i18nbug/node_modules/.pnpm/vite@4.1.1/node_modules/vite/dist/node/chunks/dep-3007b26d.js:21487:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.resolveId (file:///E:/Projects/TEST/i18nbug/node_modules/.pnpm/vite@4.1.1/node_modules/vite/dist/node/chunks/dep-3007b26d.js:41587:32)
      at async TransformContext.resolve (file:///E:/Projects/TEST/i18nbug/node_modules/.pnpm/vite@4.1.1/node_modules/vite/dist/node/chunks/dep-3007b26d.js:41334:23)
```

### Logs

```sh
X [ERROR] [plugin externalize-deps] Missing "./utils" specifier in "typesafe-i18n" package

    node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:1365:27:
      1365 │         let result = await callback({
           ╵                            ^

    at e (file:///.../node_modules/.pnpm/vite@4.1.1_f5vcjb3akvjdur4ffzogu2hewu/node_modules/vite/dist/node/chunks/dep-3007b26d.js:14845:25)
    at n (file:///.../node_modules/.pnpm/vite@4.1.1_f5vcjb3akvjdur4ffzogu2hewu/node_modules/vite/dist/node/chunks/dep-3007b26d.js:14845:627)
    at o (file:///.../node_modules/.pnpm/vite@4.1.1_f5vcjb3akvjdur4ffzogu2hewu/node_modules/vite/dist/node/chunks/dep-3007b26d.js:14845:1276)
    at resolveExports (file:///.../node_modules/.pnpm/vite@4.1.1_f5vcjb3akvjdur4ffzogu2hewu/node_modules/vite/dist/node/chunks/dep-3007b26d.js:22032:20)
    at resolveDeepImport (file:///.../node_modules/.pnpm/vite@4.1.1_f5vcjb3akvjdur4ffzogu2hewu/node_modules/vite/dist/node/chunks/dep-3007b26d.js:22051:31)        
    at tryNodeResolve (file:///.../node_modules/.pnpm/vite@4.1.1_f5vcjb3akvjdur4ffzogu2hewu/node_modules/vite/dist/node/chunks/dep-3007b26d.js:21736:20)
    at file:///.../node_modules/.pnpm/vite@4.1.1_f5vcjb3akvjdur4ffzogu2hewu/node_modules/vite/dist/node/chunks/dep-3007b26d.js:62257:40
    at requestCallbacks.on-resolve (...\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1365:28)
    at handleRequest (...\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:727:19)
    at handleIncomingPacket (...\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:749:7)

  This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:1287:20:
      1287 │       let promise = setup({
           ╵                     ^

    at setup (file:///.../node_modules/.pnpm/vite@4.1.1_f5vcjb3akvjdur4ffzogu2hewu/node_modules/vite/dist/node/chunks/dep-3007b26d.js:62246:27)
    at handlePlugins (...\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1287:21)
    at buildOrServeImpl (...\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:974:5)
    at Object.buildOrServe (...\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:780:5)
    at ...\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:2132:17
    at new Promise (<anonymous>)
    at Object.build (...\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:2131:14)
    at build (...\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1978:51)
    at bundleConfigFile (file:///.../node_modules/.pnpm/vite@4.1.1_f5vcjb3akvjdur4ffzogu2hewu/node_modules/vite/dist/node/chunks/dep-3007b26d.js:62210:26)

  The plugin "externalize-deps" was triggered by this import

    src/lib/i18n/i18n-util.ts:8:37:
      8 │ import { initExtendDictionary } from 'typesafe-i18n/utils'
        ╵                                      ~~~~~~~~~~~~~~~~~~~~~

failed to load config from ...\vite.config.ts
error when starting dev server:
Error: Build failed with 1 error:
node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:1365:27: ERROR: [plugin: externalize-deps] Missing "./utils" specifier in "typesafe-i18n" package
    at failureErrorWithLog (...\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1604:15)
    at ...\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1056:28
    at runOnEndCallbacks (...\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1476:61)
    at buildResponseToResult (...\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1054:7)
    at ...\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1166:14
    at responseCallbacks.<computed> (...\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:701:9)
    at handleIncomingPacket (...\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:756:9)
    at Socket.readFromStdout (...\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:677:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
 ELIFECYCLE  Command failed with exit code 1.
ERROR: "vite" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.
```
```


### Config

```JSON
{
   "$schema": "https://unpkg.com/typesafe-i18n@5.23.0/schema/typesafe-i18n.json",
   "adapter": "svelte",
   "outputPath": "./src/lib/i18n/",
   "baseLocale": "sv"
}
```

### Additional information

Latest SvelteKit.

**Comment by ciscoheat** [comment]
Everything works again when downgrading to 5.22.0.

**Comment by ivanhofer** [comment]
`5.23.1` should work again

**Comment by Cluster2a** [comment]
@ivanhofer, after upgrading to 5.23.1, i am getting this error:
![image](https://user-images.githubusercontent.com/84905165/216810848-721ea967-4702-4d3b-a63a-9ecdce46a15a.png)

**Comment by ivanhofer** [comment]
let's move the discussion to #592

**Comment by ciscoheat** [comment]
Confirmed that it's working with 5.23.2.
